
{ pkgs }: {
  deps = [
    pkgs.xorg.xorgserver
    pkgs.jq
    pkgs.gir-rs
    pkgs.libxkbcommon
    pkgs.glib
    pkgs.lsof
    pkgs.nss
    pkgs.nspr
    pkgs.chromium
    pkgs.alsaLib
    pkgs.atk
    pkgs.at-spi2-atk
    pkgs.cairo
    pkgs.cups
    pkgs.dbus
    pkgs.expat
    pkgs.fontconfig
    pkgs.freetype
    pkgs.gdk-pixbuf
    pkgs.gtk3
    pkgs.pango
    pkgs.xorg.libX11
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXcursor
    pkgs.xorg.libXdamage
    pkgs.xorg.libXext
    pkgs.xorg.libXfixes
    pkgs.xorg.libXi
    pkgs.xorg.libXrandr
    pkgs.xorg.libXrender
    pkgs.xorg.libXtst
    pkgs.xorg.libxcb
    pkgs.libuuid
    pkgs.mesa
  ];
}
