CREATE TABLE "cve_data" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cve_id" text NOT NULL,
	"api_id" uuid NOT NULL,
	"severity_level" text,
	"severity_score" integer,
	"cvss_score" numeric(3, 1),
	"title" text NOT NULL,
	"overview" text,
	"background_details" text,
	"threat_details" text,
	"mitigation_details" text,
	"affected_products" jsonb,
	"threat_categories" jsonb,
	"problem_types" jsonb,
	"keywords" jsonb,
	"publish_date" timestamp,
	"last_modified_date" timestamp,
	"nvd_published_date" timestamp,
	"ingested_at" timestamp DEFAULT now() NOT NULL,
	"is_kev" boolean DEFAULT false,
	"kev_date_added" timestamp,
	"kev_due_date" timestamp,
	"required_action" text,
	"known_ransomware_use" boolean DEFAULT false,
	"awaiting_enrichment" boolean DEFAULT false,
	"analysis_version" text,
	"vuln_status" text,
	"official_urls" jsonb,
	"references" jsonb,
	"author" text,
	"source_metadata" jsonb,
	"is_new" boolean DEFAULT false,
	"show_analysis_badge" boolean DEFAULT false,
	"show_kev_badge" boolean DEFAULT false,
	"data_version" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cve_data_cve_id_unique" UNIQUE("cve_id")
);
--> statement-breakpoint
CREATE TABLE "global_apis" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"provider_type" text NOT NULL,
	"base_url" text NOT NULL,
	"auth_config" jsonb,
	"rate_limit_config" jsonb,
	"status" text DEFAULT 'active' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"last_sync_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "global_apis_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "cve_data" ADD CONSTRAINT "cve_data_api_id_global_apis_id_fk" FOREIGN KEY ("api_id") REFERENCES "public"."global_apis"("id") ON DELETE no action ON UPDATE no action;